name: deploy-infrastructure

on:
    push:
        branches:
            - master
        paths:
            - 'packages/infrastructure/**'

defaults:
    run:
        working-directory: packages/infrastructure

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm install
            - run: npm run full-house
              env:
                  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
                  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                  AWS_ACCOUNT: ${{secrets.AWS_ACCOUNT}}
                  AWS_REGION: ${{secrets.AWS_REGION}}
